version: '2'
services:
    web:
        build: docker/nginx/
        ports:
            - "8082:80"
        links:
            - phpfpm
        volumes_from:
            - app
    phpfpm:
        build: docker/php-fpm/
        ports:
            - "9014:9000"
        volumes_from:
            - app
        links:
            - db
    phpcli: # use a FPM image for CLI because we don't need more..
        build: docker/php-fpm/
        volumes_from:
            - app
        links:
            - db
            - web
    app:
        build: docker/app/
        volumes:
            - ./:/app
        tty: true
    db:
        build: docker/mariadb/
        volumes_from:
            - app
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'gallery'